/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as DashboardCodesIndexRouteImport } from './routes/dashboard.codes.index'
import { Route as DashboardCodesNewRouteImport } from './routes/dashboard.codes.new'
import { Route as DashboardCodesIdRouteImport } from './routes/dashboard.codes.$id'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminStatsRouteImport } from './routes/dashboard.admin.stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCodesIndexRoute = DashboardCodesIndexRouteImport.update({
  id: '/codes/',
  path: '/codes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCodesNewRoute = DashboardCodesNewRouteImport.update({
  id: '/codes/new',
  path: '/codes/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCodesIdRoute = DashboardCodesIdRouteImport.update({
  id: '/codes/$id',
  path: '/codes/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminStatsRoute = DashboardAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdRoute
  '/dashboard/codes/new': typeof DashboardCodesNewRoute
  '/dashboard/codes': typeof DashboardCodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdRoute
  '/dashboard/codes/new': typeof DashboardCodesNewRoute
  '/dashboard/codes': typeof DashboardCodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdRoute
  '/dashboard/codes/new': typeof DashboardCodesNewRoute
  '/dashboard/codes/': typeof DashboardCodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes/$id'
    | '/dashboard/codes/new'
    | '/dashboard/codes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes/$id'
    | '/dashboard/codes/new'
    | '/dashboard/codes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes/$id'
    | '/dashboard/codes/new'
    | '/dashboard/codes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SeedRoute: typeof SeedRoute
  SignInRoute: typeof SignInRoute
  CIdRoute: typeof CIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/codes/': {
      id: '/dashboard/codes/'
      path: '/codes'
      fullPath: '/dashboard/codes'
      preLoaderRoute: typeof DashboardCodesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/codes/new': {
      id: '/dashboard/codes/new'
      path: '/codes/new'
      fullPath: '/dashboard/codes/new'
      preLoaderRoute: typeof DashboardCodesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/codes/$id': {
      id: '/dashboard/codes/$id'
      path: '/codes/$id'
      fullPath: '/dashboard/codes/$id'
      preLoaderRoute: typeof DashboardCodesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/stats': {
      id: '/dashboard/admin/stats'
      path: '/admin/stats'
      fullPath: '/dashboard/admin/stats'
      preLoaderRoute: typeof DashboardAdminStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminStatsRoute: typeof DashboardAdminStatsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardCodesIdRoute: typeof DashboardCodesIdRoute
  DashboardCodesNewRoute: typeof DashboardCodesNewRoute
  DashboardCodesIndexRoute: typeof DashboardCodesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminStatsRoute: DashboardAdminStatsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardCodesIdRoute: DashboardCodesIdRoute,
  DashboardCodesNewRoute: DashboardCodesNewRoute,
  DashboardCodesIndexRoute: DashboardCodesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SeedRoute: SeedRoute,
  SignInRoute: SignInRoute,
  CIdRoute: CIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
