/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuildRouteImport } from './routes/build'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardNewCodeRouteImport } from './routes/dashboard.new-code'
import { Route as DashboardCodesRouteImport } from './routes/dashboard.codes'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as DashboardCodesIndexRouteImport } from './routes/dashboard.codes.index'
import { Route as DashboardCodesIdRouteImport } from './routes/dashboard.codes.$id'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminStatsRouteImport } from './routes/dashboard.admin.stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCodesIdIndexRouteImport } from './routes/dashboard.codes.$id.index'
import { Route as DashboardCodesIdEditRouteImport } from './routes/dashboard.codes.$id.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewCodeRoute = DashboardNewCodeRouteImport.update({
  id: '/new-code',
  path: '/new-code',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCodesRoute = DashboardCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => DashboardRoute,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCodesIndexRoute = DashboardCodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCodesRoute,
} as any)
const DashboardCodesIdRoute = DashboardCodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCodesRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminStatsRoute = DashboardAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCodesIdIndexRoute = DashboardCodesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCodesIdRoute,
} as any)
const DashboardCodesIdEditRoute = DashboardCodesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardCodesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard/codes': typeof DashboardCodesRouteWithChildren
  '/dashboard/new-code': typeof DashboardNewCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdRouteWithChildren
  '/dashboard/codes/': typeof DashboardCodesIndexRoute
  '/dashboard/codes/$id/edit': typeof DashboardCodesIdEditRoute
  '/dashboard/codes/$id/': typeof DashboardCodesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard/new-code': typeof DashboardNewCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes': typeof DashboardCodesIndexRoute
  '/dashboard/codes/$id/edit': typeof DashboardCodesIdEditRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/seed': typeof SeedRoute
  '/sign-in': typeof SignInRoute
  '/c/$id': typeof CIdRoute
  '/dashboard/codes': typeof DashboardCodesRouteWithChildren
  '/dashboard/new-code': typeof DashboardNewCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/stats': typeof DashboardAdminStatsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/codes/$id': typeof DashboardCodesIdRouteWithChildren
  '/dashboard/codes/': typeof DashboardCodesIndexRoute
  '/dashboard/codes/$id/edit': typeof DashboardCodesIdEditRoute
  '/dashboard/codes/$id/': typeof DashboardCodesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/dashboard'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard/codes'
    | '/dashboard/new-code'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes/$id'
    | '/dashboard/codes/'
    | '/dashboard/codes/$id/edit'
    | '/dashboard/codes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard/new-code'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes'
    | '/dashboard/codes/$id/edit'
    | '/dashboard/codes/$id'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/dashboard'
    | '/seed'
    | '/sign-in'
    | '/c/$id'
    | '/dashboard/codes'
    | '/dashboard/new-code'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/stats'
    | '/dashboard/admin/users'
    | '/dashboard/codes/$id'
    | '/dashboard/codes/'
    | '/dashboard/codes/$id/edit'
    | '/dashboard/codes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SeedRoute: typeof SeedRoute
  SignInRoute: typeof SignInRoute
  CIdRoute: typeof CIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new-code': {
      id: '/dashboard/new-code'
      path: '/new-code'
      fullPath: '/dashboard/new-code'
      preLoaderRoute: typeof DashboardNewCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/codes': {
      id: '/dashboard/codes'
      path: '/codes'
      fullPath: '/dashboard/codes'
      preLoaderRoute: typeof DashboardCodesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/codes/': {
      id: '/dashboard/codes/'
      path: '/'
      fullPath: '/dashboard/codes/'
      preLoaderRoute: typeof DashboardCodesIndexRouteImport
      parentRoute: typeof DashboardCodesRoute
    }
    '/dashboard/codes/$id': {
      id: '/dashboard/codes/$id'
      path: '/$id'
      fullPath: '/dashboard/codes/$id'
      preLoaderRoute: typeof DashboardCodesIdRouteImport
      parentRoute: typeof DashboardCodesRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/stats': {
      id: '/dashboard/admin/stats'
      path: '/admin/stats'
      fullPath: '/dashboard/admin/stats'
      preLoaderRoute: typeof DashboardAdminStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/codes/$id/': {
      id: '/dashboard/codes/$id/'
      path: '/'
      fullPath: '/dashboard/codes/$id/'
      preLoaderRoute: typeof DashboardCodesIdIndexRouteImport
      parentRoute: typeof DashboardCodesIdRoute
    }
    '/dashboard/codes/$id/edit': {
      id: '/dashboard/codes/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/codes/$id/edit'
      preLoaderRoute: typeof DashboardCodesIdEditRouteImport
      parentRoute: typeof DashboardCodesIdRoute
    }
  }
}

interface DashboardCodesIdRouteChildren {
  DashboardCodesIdEditRoute: typeof DashboardCodesIdEditRoute
  DashboardCodesIdIndexRoute: typeof DashboardCodesIdIndexRoute
}

const DashboardCodesIdRouteChildren: DashboardCodesIdRouteChildren = {
  DashboardCodesIdEditRoute: DashboardCodesIdEditRoute,
  DashboardCodesIdIndexRoute: DashboardCodesIdIndexRoute,
}

const DashboardCodesIdRouteWithChildren =
  DashboardCodesIdRoute._addFileChildren(DashboardCodesIdRouteChildren)

interface DashboardCodesRouteChildren {
  DashboardCodesIdRoute: typeof DashboardCodesIdRouteWithChildren
  DashboardCodesIndexRoute: typeof DashboardCodesIndexRoute
}

const DashboardCodesRouteChildren: DashboardCodesRouteChildren = {
  DashboardCodesIdRoute: DashboardCodesIdRouteWithChildren,
  DashboardCodesIndexRoute: DashboardCodesIndexRoute,
}

const DashboardCodesRouteWithChildren = DashboardCodesRoute._addFileChildren(
  DashboardCodesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCodesRoute: typeof DashboardCodesRouteWithChildren
  DashboardNewCodeRoute: typeof DashboardNewCodeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminStatsRoute: typeof DashboardAdminStatsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCodesRoute: DashboardCodesRouteWithChildren,
  DashboardNewCodeRoute: DashboardNewCodeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminStatsRoute: DashboardAdminStatsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SeedRoute: SeedRoute,
  SignInRoute: SignInRoute,
  CIdRoute: CIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
